#include "IntList.h"

#include <iostream>
using namespace std;
// -9 -9 -7 -5 -5 -4 -3 1 3 4 6 8 9 12 13 13 13 15 15 15 16 18 19
int main(){
	IntList list;
	cout << "List constructor has been called." << endl;
	
	cout << "Inserting -9" << endl;
	list.insert_ordered( -9 );
	list.display();
	cout << endl;
	cout << "Inserting -9" << endl;
	list.insert_ordered( -9 );
	list.display();
	cout << endl;
	cout << "Inserting -7" << endl;
	list.insert_ordered( -7 );
	list.display();
	cout << endl;
	cout << "Inserting -5" << endl;
	list.insert_ordered( -5 );
	list.display();
	cout << endl;
	cout << "Inserting -5" << endl;
	list.insert_ordered(-5);
	list.display();
	cout << endl;
	cout << "Inserting -4" << endl;
	list.insert_ordered(-4);
	list.display();
	cout << endl;
	cout << "Inserting -3" << endl;
	list.insert_ordered(-3);
	list.display();
	cout << endl;
	cout << "Inserting 1" << endl;
	list.insert_ordered(1);
	list.display();
	cout << endl;
	cout << "Inserting 3" << endl;
	list.insert_ordered(3);
	list.display();
	cout << endl;
	cout << "Inserting 4" << endl;
	list.insert_ordered(4);
	list.display();
	cout << endl;
	cout << "Inserting 6" << endl;
	list.insert_ordered(6);
	list.display();
	cout << endl;
	cout << "Inserting 8" << endl;
	list.insert_ordered(8);
	list.display();
	cout << endl;
	cout << "Inserting 9" << endl;
	list.insert_ordered(9);
	list.display();
	cout << endl;
	cout << "Inserting 12" << endl;
	list.insert_ordered(12);
	list.display();
	cout << endl;
	cout << "Inserting 13" << endl;
	list.insert_ordered(13);
	list.display();
	cout << endl;
	cout << "Inserting 13" << endl;
	list.insert_ordered(13);
	list.display();
	cout << endl;
	cout << "Inserting 13" << endl;
	list.insert_ordered(13);
	list.display();
	cout << endl;
	cout << "Inserting 15" << endl;
	list.insert_ordered(15);
	list.display();
	cout << endl;
	cout << "Inserting 15" << endl;
	list.insert_ordered(15);
	list.display();
	cout << endl;
	cout << "Inserting 15" << endl;
	list.insert_ordered(15);
	list.display();
	cout << endl;
	cout << "Inserting 16" << endl;
	list.insert_ordered(16);
	list.display();
	cout << endl;
	cout << "Inserting 18" << endl;
	list.insert_ordered(18);
	list.display();
	cout << endl;
	cout << "Inserting 19" << endl;
	list.insert_ordered(19);
	list.display();
	cout << endl;
	
	return 0;
}
